import type { Metadata } from "next";
import ProtectedRoute from "@/components/ProtectedRoute";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ProtectedRoute>
     
        <main>
  <div className="">
            <div className="">
              <div className="">
              {children}
                </div>
              </div>
            </div>
         

        </main>
        

    </ProtectedRoute>
      </body>

    </html>
  );
}
